# Generated by Django 2.2.1 on 2020-02-16 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='学生姓名')),
                ('age', models.IntegerField(verbose_name='学生年龄')),
            ],
            options={
                'db_table': 'person',
                'verbose_name_plural': '学生表',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='老师姓名')),
                ('gender', models.IntegerField(verbose_name='性别')),
                ('age', models.IntegerField(verbose_name='年龄')),
                ('per', models.ManyToManyField(to='apptable.Person')),
            ],
            options={
                'db_table': 'teacher',
                'verbose_name_plural': '老师表',
            },
        ),
    ]
