# Generated by Django 2.2.1 on 2020-02-16 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apptable', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='per',
            new_name='person',
        ),
    ]
